# Generated by Django 5.0.6 on 2024-05-27 12:58

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('short_description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='dress/product_cover/', verbose_name='Dress Image')),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Time of Creation')),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
